In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("chhattisgarh_schools.csv")

In [3]:
df.head()

,School Name,Address,Phone,Website,Rating,Google Maps URL,District,Search Type
0,Gurukul School Balod,"\nP6H2+4QM, Balod, Chhattisgarh 491226",NaN,http://gurukul.imiracle.in/,NaN,https://www.google.com/maps/place/Gurukul+Scho...,Balod,schools
1,Sanskar Shala School,"\nP5FX+XV6, Balod, Chhattisgarh 491226",\n099819 86989,NaN,4.6 stars,https://www.google.com/maps/place/Sanskar+Shal...,Balod,schools
2,Mahaveer English Medium School,"\nP6J5+VC7, Balod, Chhattisgarh 491226",NaN,NaN,NaN,https://www.google.com/maps/place/Mahaveer+Eng...,Balod,schools
3,Kanha Public School,"\nP6M3+RPP, Balod, Chhattisgarh 491226",NaN,NaN,3.8 stars,https://www.google.com/maps/place/Kanha+Public...,Balod,schools
4,"Junior DPS Balod - Play Group, Nursery, LKG an...","\nSindhu Bhawan, Balod, Chhattisgarh 491226",NaN,https://www.facebook.com/JuniorDPSBalod/,5.0 stars,https://www.google.com/maps/place/Junior+DPS+B...,Balod,schools

In [4]:
df.shape

(1659, 8)

In [7]:
duplicate_count = df.duplicated(
    subset=["School Name", "Google Maps URL"]
).sum()
duplicate_count

np.int64(0)

In [9]:
df = df[
    df["Phone"].notna() & 
    (df["Phone"].astype(str).str.strip() != "")
    ]

In [10]:
df.shape

(411, 8)

In [11]:
# CLEAN PHONE COLUMNS
df["Phone"] = (
    df["Phone"]
    .astype(str)
    .str.replace(r"[^\d\s]","",regex=True)
    .str.strip()
)

display(df[["Phone"]].head())

           Phone
1   099819 86989
12  094255 61084
14  077492 22076
15  099817 96438
16  062630 79778

In [13]:
# SAVE CLEANED FILE
df.to_csv(
    "chhattisgarh_schools_cleaned.csv",
    index=False
)